name: hesen
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^14.7.20
  firebase_analytics: any
  firebase_core: ^2.32.0
  http: any
  video_player: ^2.4.5
  intl: ^0.20.0
  permission_handler: ^11.3.1
  url_launcher: ^6.2.5
  font_awesome_flutter: any
  cached_network_image: ^3.2.3
  wakelock_plus: ^1.2.8
  chewie: ^1.2.2 # Using chewie as it's a bit simpler
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.1
  carousel_slider: ^5.0.0
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.11
  curved_navigation_bar: ^1.0.6
  day_night_switch: ^1.0.4
  lottie: ^3.2.0
  uuid: ^4.3.3
  shared_preferences: ^2.3.4
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sun.png
    - assets/moon.png
    - assets/ball.png
    - assets/tv.png
    - assets/replay.png
    - assets/maximize.png
 # Place you logo there
